name: Node CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: 'Checkout Project'
        uses: 'actions/checkout@v3.0.1'
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'actions/setup-node@v3.1.1'
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install Dependencies'
        run: 'npm ci'

      - name: Lint Files with ESLint
        run: 'npm run lint'

      - name: Check Files Format with Prettier
        run: 'npm run format'

      - name: 'Run Tests and Coverage'
        env:
          CI: true
        run: 'npm run coverage'
